const {
  REACT_APP_API_URL,
  REACT_APP_PASSBASE_SECRET,
  REACT_APP_PASSBASE_KEY,
  REACT_APP_OTHER_HOST,
  REACT_APP_HOST,
  REACT_APP_HELPA,
  REACT_APP_AGENT,
  REACT_APP_TEST,
  REACT_APP_FACEBOOK_ID,
  REACT_APP_FACEBOOK_SECRET,
  REACT_APP_GOOGLE_KEY,
  REACT_APP_GOOGLE_SECRET,
  REACT_APP_GOOGLE_ID,
  REACT_APP_LINKEDIN_SECRET,
  REACT_APP_LINKEDIN_REDIRECT_URL,
  REACT_APP_LINKEDIN_ID,
  REACT_APP_STRIPE_SK,
  REACT_APP_STRIPE_PK,
  REACT_APP_SANDBOX_BACKEND_URL,
  REACT_APP_PRODUCTION_BACKEND_URL
} = process.env

const SANDBOX_BACKEND_URL = `${REACT_APP_SANDBOX_BACKEND_URL}`
const PRODUCTION_BACKEND_URL = `${REACT_APP_PRODUCTION_BACKEND_URL}`

const AGENT = `${REACT_APP_AGENT}`
const HELPA = `${REACT_APP_HELPA}`
const HOST = `${REACT_APP_HOST}`
const BACKEND_URL =`${REACT_APP_API_URL}`
const OTHER_HOST = `${REACT_APP_OTHER_HOST}`
let MEMBERS_LOGIN, JOIN_US = null
const PASSBASE_KEY = `${REACT_APP_PASSBASE_KEY}`
const PASSBASE_SECRET = `${REACT_APP_PASSBASE_SECRET}`
export default {
  BACKEND_URL: BACKEND_URL,
  API_URL: BACKEND_URL + '/',
  AGENT,
  HELPA,
  HOST,
  TEST: `${REACT_APP_TEST}`,
  OTHER_HOST: OTHER_HOST,
  facebook: {
    id: `${REACT_APP_FACEBOOK_ID}`,
    secret: `${REACT_APP_FACEBOOK_SECRET}`
  },
  google: {
    id: `${REACT_APP_GOOGLE_ID}`,
    secret: `${REACT_APP_GOOGLE_SECRET}`,
    key: `${REACT_APP_GOOGLE_KEY}`
  },
  linkedIn: {
    id: `${REACT_APP_LINKEDIN_ID}`,
    secret: `${REACT_APP_LINKEDIN_SECRET}`,
    redirectUrl: `${REACT_APP_LINKEDIN_REDIRECT_URL}`
  },
  stripe: {
    sk: `${REACT_APP_STRIPE_SK}`,
    pk: `${REACT_APP_STRIPE_PK}`
  },
  PASSBASE_KEY: PASSBASE_KEY,
  PASSBASE_SECRET: PASSBASE_SECRET
}
